import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createMigration,OLD_REVISIONS,TARGET_REVISION} from '../scripts/migrate-progress.mjs';
function fixture(t,{revision=OLD_REVISIONS[1],lesson=10,step='10.2 — connect',complete=[],runtime='nodejs',extra='',prepared='0–9'}={}){
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cap-migration-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const bank=path.join(root,'memory-bank');fs.mkdirSync(path.join(bank,'receipts'),{recursive:true});fs.mkdirSync(path.join(root,'IncidentManagement'));fs.writeFileSync(path.join(root,'IncidentManagement/keep.txt'),'Learner app: do not rebuild');
 const shared=`stateVersion: 1\ncourseRevision: ${revision}\nlearningPath: application-mcp\npreparationStatus: verified\npreparedLessons: ${prepared}\ncoreStatus: completed\nextensionStatus: in-progress\n`;
 const active=`# Active Context\n${shared}runtime: ${runtime}\nplatform: darwin\ncurrentLesson: ${lesson}\ncurrentStep: ${step}\nstatus: in-progress\nlastCompleted: 10.1 connection inspected\nnextStep: finish exact unfinished subtask\nlastVerifiedResult: actual saved result\npendingChecks: query output and handler HTTP test\npendingConfirmation: not-approved; record INC-42\n${extra}`;
 const progress=`# Course Progress\n\n## Status: in-progress\n${shared}\n### Completed Lessons\n${Array.from({length:13},(_,n)=>`- [${complete.includes(n)?'x':' '}] Lesson ${n}: Old lesson ${n}${n>0&&n<10?' (prepared by agent; not studied)':''}`).join('\n')}\nlastVerifiedResult: original progress evidence\npendingChecks: original progress pending tests\n`;
 fs.writeFileSync(path.join(bank,'activeContext.md'),active);fs.writeFileSync(path.join(bank,'progress.md'),progress);
 for(const n of [0,9,10,11,12])fs.writeFileSync(path.join(bank,'receipts',`${runtime}-${n}-1.md`),`Old revision ${revision}, lesson ${n}: actual original contents`);
 return {root,bank,active,progress,api:createMigration(root),read:n=>fs.readFileSync(path.join(bank,n),'utf8')};
}
test('dry-run is deterministic and writes no files',t=>{const f=fixture(t);const before=fs.readdirSync(f.bank,{recursive:true});assert.deepEqual(f.api.plan(),f.api.plan());assert.deepEqual(fs.readdirSync(f.bank,{recursive:true}),before);assert.equal(f.read('activeContext.md'),f.active);assert.equal(f.read('progress.md'),f.progress);});
test('all known revisions stage for review without asserting fresh verification',t=>{for(const revision of OLD_REVISIONS.filter(r=>r!=='feedback-123-2026-09-26')){const f=fixture(t,{revision,complete:[0,10,11,12],lesson:12,step:'12.3 — verify exact action'});const p=f.api.apply();assert.equal(p.status,'review-pending');assert.deepEqual(p.completionCandidates,[10,11]);const a=f.read('activeContext.md'),s=f.read('progress.md');assert.match(a,/currentLesson: 11\n/);assert.match(a,/currentStep: 11.3 — verify exact action/);assert.match(a,new RegExp(`courseRevision: ${revision}`));assert.match(a,new RegExp(`migrationTargetRevision: ${TARGET_REVISION}`));assert.match(a,/migrationReview: pending/);assert.match(a,/do not replay mutations/);assert.match(s,/- \[x\] Lesson 0:/);assert.match(s,/- \[ \] Lesson 10:/);assert.match(s,/- \[ \] Lesson 11:/);assert.match(s,/Lesson 12:/);assert.equal(f.read(path.join(p.backup,'activeContext.md')),f.active);assert.equal(f.read(path.join(p.backup,'progress.md')),f.progress);}});
test('old connection completion alone resumes query step 10.3',t=>{const f=fixture(t,{complete:[10]});const p=f.api.apply();assert.equal(p.checkpoint.step,'10.3 — query exercises');assert.deepEqual(p.completionCandidates,[]);assert.match(f.read('activeContext.md'),/migrationOriginalStep: 10.2 — connect/);});
test('in-progress old query preserves exact unfinished subtask and pending confirmation',t=>{const f=fixture(t,{lesson:11,step:'11.4 — filter by priority, then count',complete:[0,10]});f.api.apply();const a=f.read('activeContext.md');assert.match(a,/currentLesson: 10\n/);assert.match(a,/currentStep: 10.3/);assert.match(a,/migrationOriginalStep: 11.4 — filter by priority, then count/);assert.match(a,/pendingConfirmation: not-approved; record INC-42/);assert.match(a,/pendingChecks: query output and handler HTTP test/);assert.match(a,/lastVerifiedResult: actual saved result/);assert.match(f.read('progress.md'),/pendingChecks: original progress pending tests/);});
test('old query completion can never imply completed new action',t=>{const f=fixture(t,{lesson:11,step:'11.5 — saved query results',complete:[10,11]});const p=f.api.apply();assert.deepEqual(p.completionCandidates,[10]);assert.doesNotMatch(f.read('progress.md'),/- \[x\] Lesson 11:/);assert.equal(fs.existsSync(path.join(f.bank,'receipts/nodejs-11-1.md')),false);assert.match(f.read(`receipts/legacy/${OLD_REVISIONS[1]}/nodejs-11-1.md`),/lesson 11: actual original contents/);});
test('legacy Java short route, prepared versus studied, and app bytes are preserved',t=>{const f=fixture(t,{runtime:'java',extra:'shortJava: true\n',complete:[0],prepared:'0–9'});f.api.apply();assert.match(f.read('activeContext.md'),/runtime: java/);assert.match(f.read('activeContext.md'),/shortJava: true/);assert.match(f.read('activeContext.md'),/preparedLessons: 0–9/);assert.match(f.read('progress.md'),/- \[ \] Lesson 9: Old lesson 9 \(prepared by agent; not studied\)/);assert.equal(fs.readFileSync(path.join(f.root,'IncidentManagement/keep.txt'),'utf8'),'Learner app: do not rebuild');});
test('backs up every receipt, archives old extension and preserves foundation evidence paths',t=>{const f=fixture(t);const p=f.api.apply();for(const n of [0,9,10,11,12])assert.equal(f.read(`${p.backup}/receipts/nodejs-${n}-1.md`),`Old revision ${OLD_REVISIONS[1]}, lesson ${n}: actual original contents`);for(const n of [0,9])assert.ok(fs.existsSync(path.join(f.bank,`receipts/nodejs-${n}-1.md`)));assert.equal(fs.readdirSync(path.join(f.bank,'receipts/legacy',OLD_REVISIONS[1])).length,3);});
test('repeated apply is a no-op while pending and after teacher finalizes revision',t=>{const f=fixture(t);f.api.apply();const before=f.read('activeContext.md');assert.equal(f.api.apply().status,'review-pending');assert.equal(f.read('activeContext.md'),before);assert.equal(fs.readdirSync(path.join(f.bank,'migrations')).length,1);for(const n of ['activeContext.md','progress.md'])fs.writeFileSync(path.join(f.bank,n),f.read(n).replace(`courseRevision: ${OLD_REVISIONS[1]}`,`courseRevision: ${TARGET_REVISION}`));assert.equal(f.api.apply().status,'review-pending');for(const n of ['activeContext.md','progress.md'])fs.writeFileSync(path.join(f.bank,n),f.read(n).replace('migrationReview: pending','migrationReview: completed'));assert.equal(f.api.apply().status,'already-current');});
test('unknown revision, inconsistent revision, unknown runtime and duplicate field fail without changes',t=>{for(const kind of ['unknown','inconsistent','runtime','duplicate']){const f=fixture(t);if(kind==='unknown')for(const n of ['activeContext.md','progress.md'])fs.writeFileSync(path.join(f.bank,n),f.read(n).replace(OLD_REVISIONS[1],'future-revision'));if(kind==='inconsistent')fs.writeFileSync(path.join(f.bank,'progress.md'),f.progress.replace(OLD_REVISIONS[1],OLD_REVISIONS[2]));if(kind==='runtime')fs.writeFileSync(path.join(f.bank,'activeContext.md'),f.active.replace('runtime: nodejs','runtime: other'));if(kind==='duplicate')fs.appendFileSync(path.join(f.bank,'activeContext.md'),'courseRevision: duplicate\n');const before=f.read('activeContext.md');assert.throws(()=>f.api.apply(),/Unknown|Inconsistent|Duplicate/);assert.equal(f.read('activeContext.md'),before);assert.equal(fs.existsSync(path.join(f.bank,'migrations')),false);}});
test('existing backup and archive destination never get overwritten',t=>{for(const kind of ['backup','receipt']){const f=fixture(t);const p=f.api.plan();const dest=path.join(f.bank,kind==='backup'?p.backup:p.receiptMoves[0].to);fs.mkdirSync(path.dirname(dest),{recursive:true});fs.writeFileSync(dest,'existing evidence');assert.throws(()=>f.api.apply(),/collision/);assert.equal(fs.readFileSync(dest,'utf8'),'existing evidence');assert.equal(f.read('activeContext.md'),f.active);}});
test('symlink receipt and migration parents cannot escape the course',t=>{for(const kind of ['receipt','parent']){const f=fixture(t);const outside=fs.mkdtempSync(path.join(os.tmpdir(),'migration-outside-'));t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));fs.writeFileSync(path.join(outside,'keep'),'preserve');if(kind==='receipt')fs.symlinkSync(path.join(outside,'keep'),path.join(f.bank,'receipts/leak.md'));else fs.symlinkSync(outside,path.join(f.bank,'migrations'));assert.throws(()=>f.api.apply(),/symlink/);assert.equal(fs.readFileSync(path.join(outside,'keep'),'utf8'),'preserve');assert.equal(f.read('activeContext.md'),f.active);}});
test('partial save is detected and cannot trigger migration twice',t=>{const f=fixture(t);const p=f.api.plan();fs.writeFileSync(path.join(f.bank,'activeContext.md'),p.state['activeContext.md']);assert.throws(()=>f.api.apply(),/Inconsistent/);assert.equal(f.read('progress.md'),f.progress);});
test('missing optional route fields default to guided without rebuilding',t=>{const f=fixture(t);for(const n of ['activeContext.md','progress.md'])fs.writeFileSync(path.join(f.bank,n),f.read(n).replace(/^(learningPath|preparedLessons|preparationStatus|coreStatus|extensionStatus): .*\n/gm,''));f.api.apply();assert.match(f.read('activeContext.md'),/learningPath: guided/);assert.match(f.read('progress.md'),/preparationStatus: not-started/);});

test('checkpoint and status disagreement fail safely before backup',t=>{for(const kind of ['step','status']){const f=fixture(t);fs.writeFileSync(path.join(f.bank,'activeContext.md'),f.active.replace(kind==='step'?'currentStep: 10.2':'status: in-progress',kind==='step'?'currentStep: 11.2':'status: completed'));assert.throws(()=>f.api.apply(),/Inconsistent/);assert.equal(fs.existsSync(path.join(f.bank,'migrations')),false);}});
test('an incomplete transaction blocks retry until explicit reconciliation',t=>{const f=fixture(t);fs.writeFileSync(path.join(f.bank,'migration-incomplete.json'),'{"backup":"preserved-evidence"}');assert.throws(()=>f.api.apply(),/Incomplete migration/);assert.equal(f.read('activeContext.md'),f.active);});

test('previously completed status is preserved as a claim while review is in progress',t=>{const f=fixture(t,{complete:[10,11,12],lesson:12,step:'12.4 — final result'});for(const n of ['activeContext.md','progress.md'])fs.writeFileSync(path.join(f.bank,n),f.read(n).replace(n==='activeContext.md'?'status: in-progress':'## Status: in-progress',n==='activeContext.md'?'status: completed':'## Status: completed'));f.api.apply();assert.match(f.read('activeContext.md'),/^status: in-progress$/m);assert.match(f.read('progress.md'),/^## Status: in-progress$/m);for(const n of ['activeContext.md','progress.md'])assert.match(f.read(n),/^migrationOriginalStatus: completed$/m);});
test('a failure saving the second state leaves original backups and blocks automatic retry',t=>{const f=fixture(t);const p=f.api.plan(),rename=fs.renameSync;let calls=0;t.mock.method(fs,'renameSync',(...args)=>{if(++calls===2)throw Error('Synthetic interrupted second save');return rename(...args);});assert.throws(()=>f.api.apply(),/Synthetic interrupted/);assert.equal(f.read(`${p.backup}/activeContext.md`),f.active);assert.equal(f.read(`${p.backup}/progress.md`),f.progress);assert.ok(fs.existsSync(path.join(f.bank,'migration-incomplete.json')));assert.throws(()=>f.api.plan(),/Incomplete migration/);assert.equal(f.read('progress.md'),f.progress);assert.equal(fs.existsSync(path.join(f.bank,'.migration.lock')),false);});

test('previous merged lessons preserve current action checkpoint and historical foundation journal',t=>{const f=fixture(t,{revision:'feedback-123-2026-09-26',lesson:11,step:'11.2 — confirmation pending',complete:[10],runtime:'java'});const journal=JSON.stringify({version:1,runtime:'java',phases:[{lesson:0}]});fs.writeFileSync(path.join(f.bank,'preparation.json'),journal);const p=f.api.apply();assert.equal(p.checkpoint.lesson,11);assert.equal(p.checkpoint.step,'11.2 — confirmation pending');assert.deepEqual(p.completionCandidates,[10]);assert.equal(f.read(`${p.backup}/preparation.json`),journal);assert.equal(f.read('preparation.json'),journal);assert.match(f.read('activeContext.md'),/routeLesson: 2/);assert.match(f.read('activeContext.md'),/preparationStatus: awaiting-foundation/);assert.match(f.read('activeContext.md'),/runtime: java/);assert.match(f.read('activeContext.md'),/pendingConfirmation: not-approved; record INC-42/);});
test('untouched previous welcome templates migrate without selecting runtime or inferring an app',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cap-welcome-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const bank=path.join(root,'memory-bank');fs.mkdirSync(bank);
 const shared='stateVersion: 1\ncourseRevision: feedback-123-2026-09-26\nlearningPath: unselected\npreparationStatus: not-started\npreparedLessons: none\ncoreStatus: not-started\nextensionStatus: not-started\n';
 const active=shared+'runtime: unselected\nplatform: unknown\ncurrentLesson: 0\ncurrentStep: welcome\nstatus: not-started\nnextStep: select learning path\n';
 const progress='## Status: not-started\n'+shared+Array.from({length:12},(_,n)=>`- [ ] Lesson ${n}: Previous lesson`).join('\n')+'\n';
 fs.writeFileSync(path.join(bank,'activeContext.md'),active);fs.writeFileSync(path.join(bank,'progress.md'),progress);
 const api=createMigration(root),result=api.apply();assert.equal(result.status,'review-pending');assert.equal(result.checkpoint.lesson,0);assert.equal(result.checkpoint.step,'welcome');assert.deepEqual(result.completionCandidates,[]);
 const saved=fs.readFileSync(path.join(bank,'activeContext.md'),'utf8');for(const line of ['runtime: unselected','platform: unknown','learningPath: unselected','status: not-started','foundationReview: not-applicable','preparedLessons: none'])assert.ok(saved.includes(line),line);
 assert.equal(fs.existsSync(path.join(root,'IncidentManagement')),false);assert.equal(fs.existsSync(path.join(bank,'preparation.json')),false);assert.equal(fs.readFileSync(path.join(bank,result.backup,'activeContext.md'),'utf8'),active);assert.equal(api.apply().status,'review-pending');
 fs.mkdirSync(path.join(root,'IncidentManagement'));assert.throws(()=>api.plan(),/Unknown runtime/);
});
