import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {createPreparation,requiredChecks,SPEC_REVISION} from '../scripts/prepare-course.mjs';
const source=path.resolve(import.meta.dirname,'../..');
function fixture(t,runtime='nodejs') {
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'cap-preparation-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));
 for(const f of ['course/BUILDER.md','course/docs','course/scripts'])fs.cpSync(path.join(source,f),path.join(root,f),{recursive:true});
 fs.mkdirSync(path.join(root,'memory-bank/receipts'),{recursive:true});fs.mkdirSync(path.join(root,'IncidentManagement'));
 fs.writeFileSync(path.join(root,'IncidentManagement/model.cds'),'entity Test {key ID: UUID;}');
 fs.writeFileSync(path.join(root,'memory-bank/activeContext.md'),`learningPath: application-mcp\nruntime: ${runtime}\n`);
 const api=createPreparation(root), log='memory-bank/receipts/check.log',receipt='memory-bank/receipts/foundation.json';
 fs.writeFileSync(path.join(root,log),'Recorded fixture results; unit evidence only');
 function record(alter={}){fs.writeFileSync(path.join(root,receipt),JSON.stringify({version:2,specRevision:SPEC_REVISION,runtime,versions:{node:'fixture',cds:'fixture'},preview:{url:'http://localhost:4004/',status:'running'},recovery:[],app:api.snapshot(),pendingChecks:[],checks:requiredChecks.map(name=>({name,status:'passed',evidence:[log]})),...alter}));return api.record(receipt);}
 return {root,api,record};
}
test('one foundation outcome contract supports both existing runtimes without lesson replay',t=>{const {root,api}=fixture(t);for(const runtime of ['nodejs','java']){const p=api.plan(runtime);assert.equal(p.spec,'course/docs/INCIDENT-APP-SPEC.md');assert.ok(p.checks.includes('browser-journey'));assert.equal(p.phases,undefined);}assert.equal(fs.existsSync(path.join(root,'memory-bank/preparation.json')),false);assert.throws(()=>api.plan('other'));});
test('incomplete evidence, pending reconnect, browser omission and failing checks block readiness',t=>{const {api,record}=fixture(t);api.start('nodejs');assert.throws(()=>api.finish(),/receipt/);for(const alter of [{pendingChecks:['native reload pending']},{checks:requiredChecks.filter(n=>n!=='browser-journey').map(name=>({name,status:'passed',evidence:['memory-bank/receipts/check.log']}))},{versions:{}},{preview:{url:'http://localhost:4004',status:'stopped'}},{checks:requiredChecks.map(name=>({name,status:'failed',evidence:[]}))}])assert.throws(()=>record(alter));assert.equal(api.status().status,'building');});
test('complete evidence readies foundation without marking any lesson studied',t=>{const {root,api,record}=fixture(t,'java');const before=fs.readFileSync(path.join(root,'memory-bank/activeContext.md'),'utf8');api.start('java');record();assert.equal(api.finish().status,'ready-for-10');assert.equal(api.start('java').status,'ready-for-10');assert.equal(fs.readFileSync(path.join(root,'memory-bank/activeContext.md'),'utf8'),before);assert.equal(api.status().phases,undefined);});
test('source edits between recording and finish cannot be blessed',t=>{const {root,api,record}=fixture(t);api.start('nodejs');record();fs.appendFileSync(path.join(root,'IncidentManagement/model.cds'),'// changed');assert.throws(()=>api.finish(),/App changed/);});
test('captured evidence is immutable while original growing log remains usable',t=>{const {root,api,record}=fixture(t);api.start('nodejs');record();fs.appendFileSync(path.join(root,'memory-bank/receipts/check.log'),'more');api.status();const captured=Object.keys(api.status().receipt.evidence)[0];fs.appendFileSync(path.join(root,captured),'tampered');assert.throws(()=>api.status(),/Evidence changed/);});
test('recipe drift and verified app drift require revalidation without rebuilding',t=>{const {root,api,record}=fixture(t);api.start('nodejs');record();api.finish();fs.appendFileSync(path.join(root,'IncidentManagement/model.cds'),'// learner edit');assert.throws(()=>api.status(),/App changed/);api.reopen();record();api.finish();fs.appendFileSync(path.join(root,'course/docs/INCIDENT-APP-SPEC.md'),'drift');assert.throws(()=>api.status(),/Recipe changed/);});
test('historical ten-phase journal is readable and backed up, never replayed',t=>{const {root,api}=fixture(t,'java');const old={version:1,runtime:'java',status:'in-progress',phases:[{lesson:0}]};fs.writeFileSync(path.join(root,'memory-bank/preparation.json'),JSON.stringify(old));assert.deepEqual(api.history(),old);assert.throws(()=>api.start('java'),/Historical/);const s=api.reopen();assert.equal(s.version,2);assert.equal(s.runtime,'java');assert.deepEqual(JSON.parse(fs.readFileSync(path.join(root,'memory-bank',s.revalidates))),old);assert.equal(s.phases,undefined);assert.ok(fs.existsSync(path.join(root,'IncidentManagement/model.cds')));});
test('evidence and app symlinks cannot escape the course',t=>{const {root,api,record}=fixture(t);api.start('nodejs');const outside=fs.mkdtempSync(path.join(os.tmpdir(),'outside-'));t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));const f=path.join(outside,'log');fs.writeFileSync(f,'outside');fs.symlinkSync(f,path.join(root,'leak.log'));for(const evidence of [[f],['leak.log']])assert.throws(()=>record({checks:requiredChecks.map(name=>({name,status:'passed',evidence}))}),/relative|inside/);fs.symlinkSync(f,path.join(root,'IncidentManagement/leak'));assert.throws(()=>api.snapshot(),/symlink/);});
test('route or runtime change blocks reuse',t=>{const {root,api,record}=fixture(t);api.start('nodejs');record();for(const state of ['learningPath: guided\nruntime: nodejs\n','learningPath: application-mcp\nruntime: java\n']){fs.writeFileSync(path.join(root,'memory-bank/activeContext.md'),state);assert.throws(()=>api.finish(),/Select/);}});
