import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import http from 'node:http';
import {spawn} from 'node:child_process';
import {installStarter} from '../scripts/install-starter.mjs';
import {checkStarter} from '../scripts/check-starter.mjs';
const source=path.resolve(import.meta.dirname,'../..');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'cap-starter-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));fs.cpSync(path.join(source,'course/starters'),path.join(root,'course/starters'),{recursive:true});return root;}
function files(root){return fs.readdirSync(root,{withFileTypes:true}).flatMap(e=>e.isDirectory()?files(path.join(root,e.name)).map(f=>path.join(e.name,f)):[e.name]).sort();}
test('installer copies the complete bundled app with exact bytes',t=>{const root=fixture(t),bundle=path.join(root,'course/starters/incident-management');installStarter(root);const dest=path.join(root,'IncidentManagement');for(const f of files(bundle)){assert.ok(fs.existsSync(path.join(dest,f)),f);assert.deepEqual(fs.readFileSync(path.join(dest,f)),fs.readFileSync(path.join(bundle,f)),f);}assert.ok(fs.existsSync(path.join(dest,'package.json')));});
test('installer refuses an existing app and never changes learner bytes',t=>{const root=fixture(t),dest=path.join(root,'IncidentManagement');fs.mkdirSync(dest);fs.writeFileSync(path.join(dest,'keep.txt'),'learner edits');assert.throws(()=>installStarter(root));assert.deepEqual(fs.readdirSync(dest),['keep.txt']);assert.equal(fs.readFileSync(path.join(dest,'keep.txt'),'utf8'),'learner edits');});
test('tampered starter contents cannot be installed',t=>{const root=fixture(t);fs.appendFileSync(path.join(root,'course/starters/incident-management/package.json'),' ');assert.throws(()=>installStarter(root));assert.equal(fs.existsSync(path.join(root,'IncidentManagement')),false);});
test('starter and destination symlinks are rejected without touching their targets',t=>{for(const kind of ['source','destination']){const root=fixture(t),outside=fs.mkdtempSync(path.join(os.tmpdir(),'cap-starter-outside-'));t.after(()=>fs.rmSync(outside,{recursive:true,force:true}));fs.writeFileSync(path.join(outside,'keep.txt'),'preserve');if(kind==='source')fs.symlinkSync(path.join(outside,'keep.txt'),path.join(root,'course/starters/incident-management/leak.txt'));else fs.symlinkSync(outside,path.join(root,'IncidentManagement'));assert.throws(()=>installStarter(root));assert.equal(fs.readFileSync(path.join(outside,'keep.txt'),'utf8'),'preserve');assert.deepEqual(fs.readdirSync(outside),['keep.txt']);}});
test('tampered manifest cannot bless missing or changed bundle files',t=>{const root=fixture(t),p=path.join(root,'course/starters/manifest.json');const m=JSON.parse(fs.readFileSync(p));m.files['package.json']='0'.repeat(64);fs.writeFileSync(p,JSON.stringify(m));assert.throws(()=>installStarter(root));assert.equal(fs.existsSync(path.join(root,'IncidentManagement')),false);});
async function server(t,override=()=>false){const requests=[];const app=http.createServer((req,res)=>{requests.push({method:req.method,url:req.url});if(override(req,res))return;const u=new URL(req.url,'http://localhost');if(u.pathname.endsWith('/$metadata')){res.setHeader('content-type','application/xml');res.end('<edmx:Edmx><EntityType Name="Incidents"/><EntityType Name="BusinessPartners"/><EntitySet Name="Incidents"/><EntitySet Name="BusinessPartners"/></edmx:Edmx>');}else if(u.pathname==='/odata/v4/incidents/Incidents'){res.setHeader('content-type','application/json');res.end(JSON.stringify({value:[{ID:'11111111-1111-4111-8111-111111111111',title:'Synthetic fixture'}]}));}else if(u.pathname==='/odata/v4/incidents/BusinessPartners'){res.setHeader('content-type','application/json');res.end(JSON.stringify({value:[{ID:'22222222-2222-4222-8222-222222222222',name:'Synthetic partner'}]}));}else if(u.pathname==='/ns.incidents/index.html'){res.setHeader('content-type','text/html');res.end('<HTML><body>Fixture preview</body></HTML>');}else if(u.pathname==='/ns.incidents/manifest.json'){res.setHeader('content-type','application/json');res.end(JSON.stringify({'sap.app':{id:'ns.incidents'}}));}else{res.statusCode=404;res.end('Unknown request');}});await new Promise(resolve=>app.listen(0,'127.0.0.1',resolve));t.after(()=>new Promise(resolve=>{app.closeAllConnections();app.close(resolve);}));return {url:`http://127.0.0.1:${app.address().port}`,requests};}
test('readiness verifies metadata, both data sets and UI using GET only',async t=>{const f=await server(t);const result=await checkStarter(f.url);assert.equal(result.pass,true,JSON.stringify(result));assert.ok(result.checks.length>=5);assert.ok(result.checks.every(c=>c.pass&&typeof c.name==='string'&&typeof c.detail==='string'));assert.equal(result.previewUrl,f.url+'/ns.incidents/index.html');assert.ok(f.requests.every(r=>r.method==='GET'));for(const endpoint of ['/$metadata','/Incidents','/BusinessPartners','/ns.incidents/index.html','/ns.incidents/manifest.json'])assert.ok(f.requests.some(r=>new URL(r.url,f.url).pathname.endsWith(endpoint)),endpoint);});
test('missing metadata, malformed/empty data and wrong UI fail readiness without mutation',async t=>{for(const scenario of ['metadata','empty-incidents','invalid-partner','html','manifest','http']){const f=await server(t,(req,res)=>{const p=new URL(req.url,'http://localhost').pathname;let body;if(scenario==='metadata'&&p.endsWith('/$metadata'))body='<EntitySet Name="Incidents"/>';if(scenario==='empty-incidents'&&p.endsWith('/Incidents'))body='{"value":[]}';if(scenario==='invalid-partner'&&p.endsWith('/BusinessPartners'))body='{"value":[{"ID":"partner"}]}';if(scenario==='html'&&p.endsWith('/index.html'))body='not an html document';if(scenario==='manifest'&&p.endsWith('/manifest.json'))body='{"sap.app":{"id":"wrong.app"}}';if(scenario==='http'&&p.endsWith('/Incidents')){res.statusCode=500;body='failed';}if(body===undefined)return false;res.end(body);return true;});const result=await checkStarter(f.url);assert.equal(result.pass,false,scenario);assert.ok(result.checks.some(c=>!c.pass),scenario);assert.ok(f.requests.every(r=>r.method==='GET'),scenario);}});
test('unsafe URLs reject before any HTTP request',async t=>{const f=await server(t);for(const url of ['https://127.0.0.1:4004','http://example.com:4004','file:///tmp/app',f.url.replace('http://','http://user:password@')])await assert.rejects(()=>checkStarter(url));assert.equal(f.requests.length,0);});
test('redirects are not followed',async t=>{const f=await server(t,(req,res)=>{res.statusCode=302;res.setHeader('location','/redirect-target');res.end();return true;});const result=await checkStarter(f.url);assert.equal(result.pass,false);assert.equal(f.requests.some(r=>r.url==='/redirect-target'),false);});
test('hung responses time out with failed checks and no writes',async t=>{const f=await server(t,()=>true);const result=await checkStarter(f.url,{timeoutMs:30});assert.equal(result.pass,false);assert.ok(result.checks.some(c=>!c.pass));assert.ok(f.requests.every(r=>r.method==='GET'));});

function runCheck(url,output){return new Promise((resolve,reject)=>{const child=spawn(process.execPath,[path.join(source,'course/scripts/check-starter.mjs'),'--url',url,'--output',output],{stdio:['ignore','pipe','pipe']});let stdout='',stderr='';child.stdout.on('data',b=>stdout+=b);child.stderr.on('data',b=>stderr+=b);child.on('error',reject);child.on('close',code=>resolve({code,stdout,stderr}));});}
test('CLI creates nested output, replaces previous receipt, and failure cannot leave stale success',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'starter-cli-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const output=path.join(dir,'nested','receipts','readiness.json');let fail=false;
 const f=await server(t,(req,res)=>{if(fail&&req.url.includes('/Incidents?')){res.statusCode=503;res.end('fixture failure');return true;}return false;});
 for(let n=0;n<2;n++){const r=await runCheck(f.url,output);assert.equal(r.code,0,r.stderr);assert.equal(JSON.parse(fs.readFileSync(output)).pass,true);assert.deepEqual(JSON.parse(r.stdout),JSON.parse(fs.readFileSync(output)));}
 fail=true;const result=await runCheck(f.url,output);assert.equal(result.code,1);const receipt=JSON.parse(fs.readFileSync(output));assert.equal(receipt.pass,false);assert.ok(receipt.checks.some(c=>!c.pass));assert.deepEqual(receipt,JSON.parse(result.stdout));assert.deepEqual(fs.readdirSync(path.dirname(output)),['readiness.json']);assert.ok(f.requests.every(r=>r.method==='GET'));
});
